# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sonify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sonify
  pod 'ProgressHUD', :git => 'https://github.com/relatedcode/ProgressHUD.git', :commit => '83c3801e9aa69be157a47c40cdd8702bfaf29213'
  pod 'CircleProgressBar', '~> 0.32’
  pod 'Pulsator'

end
